import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

export type Language = 'es' | 'en';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  es: {
    'header.login': 'Iniciar Sesión',
    'header.register': 'Registrarse',
    'header.home': 'Inicio',
    'header.events': 'Eventos',
    'header.contact': 'Contacto',
    'home.title': 'Plataforma de Gestión de Eventos',
    'home.subtitle': 'Gestiona tus eventos de forma eficiente',
    'home.cta.start': 'Comenzar Ahora',
    'home.cta.login': 'Ya tengo cuenta',
    'home.features.title': 'Todo lo que necesitas',
    'home.events.title': 'Eventos Activos',
    'home.events.subtitle': 'Descubre los próximos eventos',
    'home.howItWorks': '¿Cómo funciona?',
    'home.step1.title': 'Regístrate',
    'home.step1.desc': 'Crea tu cuenta con tus datos profesionales',
    'home.step2.title': 'Envía tu trabajo',
    'home.step2.desc': 'Sube tu resumen con título, autores y palabras clave',
    'home.step3.title': 'Recibe feedback',
    'home.step3.desc': 'Los revisores evalúan y el comité clasifica tu trabajo',
    'home.cta.ready': '¿Listo para participar?',
    'home.cta.join': 'Iniciar Sesión',
    'home.news.title': 'Noticias y Artículos',
    'home.news.viewAll': 'Ver Todos los Artículos',
    'home.events.participants': 'participantes',
    'home.events.works': 'trabajos',
    'home.events.open': 'Inscripciones Abiertas',
    'home.events.coming': 'Próximamente',
    'home.events.viewEvent': 'Ver Evento',
    'home.events.noEvents': 'No hay eventos activos en este momento',
    'home.features.abstracts': 'Gestión de Resúmenes',
    'home.features.abstracts.desc': 'Envía y gestiona tus trabajos con seguimiento en tiempo real.',
    'home.features.peerReview': 'Revisión por Pares',
    'home.features.peerReview.desc': 'Sistema de evaluación transparente con árbitros especializados.',
    'home.features.multiple': 'Múltiples Eventos',
    'home.features.multiple.desc': 'Participa en diferentes congresos desde una única plataforma.',
    'home.features.certificates': 'Certificados Digitales',
    'home.features.certificates.desc': 'Recibe certificados verificables digitalmente.',
    'event.back': 'Volver',
    'event.activities': 'Actividades y Componentes',
    'event.noSubEvents': 'No hay sub eventos disponibles',
    'event.viewDetails': 'Ver Detalles',
    'footer.rights': 'Todos los derechos reservados',
    'footer.navigation': 'Navegación',
    'footer.contact': 'Contacto',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.notFound': 'No encontrado',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.search': 'Buscar',
    '404.title': '404',
    '404.message': 'Página no encontrada',
    '404.backHome': 'Volver al inicio',
    'login.title': 'Iniciar Sesión',
    'login.subtitle': 'Ingresa tus credenciales para acceder al sistema',
    'login.email': 'Correo Electrónico',
    'login.emailPlaceholder': 'tu@email.com',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': '••••••••',
    'login.submit': 'Iniciar Sesión',
    'login.noAccount': '¿No tienes cuenta?',
    'login.register': 'Regístrate',
    'login.demoAccounts': 'Cuentas de demostración (clic para usar):',
    'login.heroTitle': 'Gestiona tus eventos de forma eficiente',
    'login.heroDesc': 'Plataforma integral para la gestión de congresos, conferencias y eventos. Desde el envío de resúmenes hasta la emisión de certificados.',
    'login.feature.registration': 'Registro Online',
    'login.feature.review': 'Revisión por Pares',
    'login.feature.program': 'Gestión de Programa',
    'login.feature.certificates': 'Certificados',
    'register.title': 'Crear Nueva Cuenta',
    'register.subtitle': 'Completa tus datos para registrarte',
    'register.password': 'Contraseña',
    'register.confirmPassword': 'Confirmar contraseña',
    'register.submit': 'REGÍSTRESE',
    'register.hasAccount': '¿Ya tienes cuenta?',
    'register.login': 'Inicia Sesión',
    'register.backLogin': 'Volver al inicio',
    'register.inscription': 'Formulario de Inscripción',
    'register.inscriptionDesc': 'Completa tus datos para inscribirte en',
    'register.heroTitle': 'Crear Nueva Cuenta',
    'register.heroDesc': 'Regístrate para participar en eventos, enviar tus trabajos y conectar con otros profesionales.',
    'register.card.submitAbstract': 'Envía Resúmenes',
    'register.card.submitAbstractDesc': 'Presenta tus trabajos',
    'register.card.peerReview': 'Revisión por Pares',
    'register.card.peerReviewDesc': 'Feedback de expertos',
    'register.card.networking': 'Networking',
    'register.card.networkingDesc': 'Conecta con colegas',
    'register.card.certificates': 'Certificados',
    'register.card.certificatesDesc': 'Reconocimiento oficial',
    'register.passwordMismatch': 'Las contraseñas no coinciden',
    'dashboard.greeting': '¡Hola,',
    'dashboard.noEvents': 'No tienes eventos asociados aún.',
    'dashboard.selectEvent': 'Selecciona un evento',
    'dashboard.eventsRegistered': 'Estás registrado en',
    'dashboard.event': 'evento',
    'dashboard.events': 'eventos',
    'dashboard.goToDashboard': 'Ir al Dashboard',
    'dashboard.daysLeft': 'Faltan',
    'dashboard.days': 'días',
    'dashboard.today': '¡Hoy!',
    'dashboard.finished': 'Finalizado',
    'dashboard.panel': 'Panel de',
    'dashboard.newAbstract': 'Nuevo Resumen',
    'dashboard.totalAbstracts': 'Total Resúmenes',
    'dashboard.inProcess': 'En Proceso',
    'dashboard.approved': 'Aprobados',
    'dashboard.pendingReview': 'Pendientes de Revisión',
    'dashboard.myRecentAbstracts': 'Mis Resúmenes Recientes',
    'dashboard.status': 'Estado actual de tus envíos',
    'dashboard.viewAll': 'Ver todos',
    'dashboard.noAbstracts': 'No hay resúmenes aún',
    'dashboard.sendFirst': 'Enviar mi primer resumen',
    'dashboard.currentEvent': 'Evento Actual',
    'dashboard.eventInfo': 'Información del evento seleccionado',
    'dashboard.role.participant': 'Participante',
    'dashboard.role.reviewer': 'Revisor',
    'dashboard.role.committee': 'Miembro del Comité',
    'dashboard.role.admin': 'Administrador',
    'dashboard.role.superadmin': 'SuperAdmin',
    'dashboard.role.adminReceptivo': 'Admin Receptivo',
    'dashboard.role.adminEmpresa': 'Admin Empresa',
    'dashboard.role.coordinadorHotel': 'Coord. Hotel',
    'dashboard.role.lectorReceptivo': 'Lector Receptivo',
    'dashboard.role.lectorEmpresa': 'Lector Empresa',
  },
  en: {
    'header.login': 'Login',
    'header.register': 'Register',
    'header.home': 'Home',
    'header.events': 'Events',
    'header.contact': 'Contact',
    'home.title': 'Event Management Platform',
    'home.subtitle': 'Manage your events efficiently',
    'home.cta.start': 'Get Started',
    'home.cta.login': 'I have an account',
    'home.features.title': 'Everything you need',
    'home.events.title': 'Active Events',
    'home.events.subtitle': 'Discover upcoming events',
    'home.howItWorks': 'How it works?',
    'home.step1.title': 'Sign up',
    'home.step1.desc': 'Create your account with your professional data',
    'home.step2.title': 'Submit your work',
    'home.step2.desc': 'Upload your abstract with title, authors and keywords',
    'home.step3.title': 'Receive feedback',
    'home.step3.desc': 'Reviewers evaluate and the committee classifies your work',
    'home.cta.ready': 'Ready to participate?',
    'home.cta.join': 'Login',
    'home.news.title': 'News and Articles',
    'home.news.viewAll': 'View All Articles',
    'home.events.participants': 'participants',
    'home.events.works': 'works',
    'home.events.open': 'Open Registration',
    'home.events.coming': 'Coming Soon',
    'home.events.viewEvent': 'View Event',
    'home.events.noEvents': 'No active events at this time',
    'home.features.abstracts': 'Abstract Management',
    'home.features.abstracts.desc': 'Send and manage your works with real-time tracking.',
    'home.features.peerReview': 'Peer Review',
    'home.features.peerReview.desc': 'Transparent evaluation system with specialized reviewers.',
    'home.features.multiple': 'Multiple Events',
    'home.features.multiple.desc': 'Participate in different congresses from a single platform.',
    'home.features.certificates': 'Digital Certificates',
    'home.features.certificates.desc': 'Receive digitally verifiable certificates.',
    'event.back': 'Back',
    'event.activities': 'Activities and Components',
    'event.noSubEvents': 'No sub events available',
    'event.viewDetails': 'View Details',
    'footer.rights': 'All rights reserved',
    'footer.navigation': 'Navigation',
    'footer.contact': 'Contact',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.notFound': 'Not found',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    '404.title': '404',
    '404.message': 'Page not found',
    '404.backHome': 'Back to home',
    'login.title': 'Login',
    'login.subtitle': 'Enter your credentials to access the system',
    'login.email': 'Email',
    'login.emailPlaceholder': 'your@email.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.submit': 'Login',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Sign up',
    'login.demoAccounts': 'Demo accounts (click to use):',
    'login.heroTitle': 'Manage your events efficiently',
    'login.heroDesc': 'Comprehensive platform for managing congresses, conferences and events. From abstract submission to certificate issuance.',
    'login.feature.registration': 'Online Registration',
    'login.feature.review': 'Peer Review',
    'login.feature.program': 'Program Management',
    'login.feature.certificates': 'Certificates',
    'register.title': 'Create New Account',
    'register.subtitle': 'Complete your details to register',
    'register.password': 'Password',
    'register.confirmPassword': 'Confirm password',
    'register.submit': 'REGISTER',
    'register.hasAccount': 'Already have an account?',
    'register.login': 'Login',
    'register.backLogin': 'Back to home',
    'register.inscription': 'Registration Form',
    'register.inscriptionDesc': 'Complete your details to register for',
    'register.heroTitle': 'Create New Account',
    'register.heroDesc': 'Sign up to participate in events, submit your work and connect with other professionals.',
    'register.card.submitAbstract': 'Submit Abstracts',
    'register.card.submitAbstractDesc': 'Present your work',
    'register.card.peerReview': 'Peer Review',
    'register.card.peerReviewDesc': 'Expert feedback',
    'register.card.networking': 'Networking',
    'register.card.networkingDesc': 'Connect with colleagues',
    'register.card.certificates': 'Certificates',
    'register.card.certificatesDesc': 'Official recognition',
    'register.passwordMismatch': 'Passwords do not match',
    'dashboard.greeting': 'Hello,',
    'dashboard.noEvents': 'You have no associated events yet.',
    'dashboard.selectEvent': 'Select an event',
    'dashboard.eventsRegistered': 'You are registered in',
    'dashboard.event': 'event',
    'dashboard.events': 'events',
    'dashboard.goToDashboard': 'Go to Dashboard',
    'dashboard.daysLeft': 'Days left',
    'dashboard.days': 'days',
    'dashboard.today': 'Today!',
    'dashboard.finished': 'Finished',
    'dashboard.panel': 'Panel of',
    'dashboard.newAbstract': 'New Abstract',
    'dashboard.totalAbstracts': 'Total Abstracts',
    'dashboard.inProcess': 'In Process',
    'dashboard.approved': 'Approved',
    'dashboard.pendingReview': 'Pending Review',
    'dashboard.myRecentAbstracts': 'My Recent Abstracts',
    'dashboard.status': 'Current status of your submissions',
    'dashboard.viewAll': 'View all',
    'dashboard.noAbstracts': 'No abstracts yet',
    'dashboard.sendFirst': 'Send my first abstract',
    'dashboard.currentEvent': 'Current Event',
    'dashboard.eventInfo': 'Selected event information',
    'dashboard.role.participant': 'Participant',
    'dashboard.role.reviewer': 'Reviewer',
    'dashboard.role.committee': 'Committee Member',
    'dashboard.role.admin': 'Administrator',
    'dashboard.role.superadmin': 'SuperAdmin',
    'dashboard.role.adminReceptivo': 'Receptive Admin',
    'dashboard.role.adminEmpresa': 'Business Admin',
    'dashboard.role.coordinadorHotel': 'Hotel Coordinator',
    'dashboard.role.lectorReceptivo': 'Receptive Reader',
    'dashboard.role.lectorEmpresa': 'Business Reader',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    const saved = localStorage.getItem('sge_language') as Language;
    if (saved && (saved === 'es' || saved === 'en')) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('sge_language', lang);
    window.dispatchEvent(new CustomEvent('sge-language-change', { detail: { language: lang } }));
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations['es']?.[key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: 'es' as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}

export { translations };
